version: "3.4"

services:
  # zookeeper service
  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  # apache service
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    restart: always
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper

  # mongo db
  mongo-container:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    container_name: mongo-container
    volumes:
      - mongodb_data_container:/data/db

  # MSSQL container
  sql-container:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql-container
    restart: always
    ports:
      - "1433:1433"
    environment:
      MSSQL_SA_PASSWORD: "$50@bs22Ev3ry_2202"
      MSSQL_PID: "Developer"
      MSSQL_USER: "SA"
      ACCEPT_EULA: "Y"
    volumes:
      - sql_container_data:/var/opt/mssql 

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongodb_data_container:
    driver: local
  sql_container_data:
    driver: local

networks:
  default:
    external:
      name: mydockernetwork
